- hosts: all
    - name: Change ownership of Tomcat installation
      file: path=/usr/local/apache-tomcat-8.0.23 owner=tomcat group=tomcat state=directory recurse=yes

    - name: Start Tomcat
      command: nohup /usr/local/apache-tomcat-8.0.23/bin/startup.sh
      become: true
      become_user: tomcat

    - name: wait for tomcat to start
      wait_for: port={{http_port}}

